---
name: CI/CD for amd64 debian package
on:
  push:
    branches:
      - 'cura/**'
    tags:
      - 'cura/v**'
  pull_request:
    branches:
      - 'cura/**'
jobs:
  build:
    name: Build debian package
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
    - name: Check repository
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update
        apt-get upgrade -y
        apt-get install -y cmake gcc g++
    - name: Build debian package
      run: |
        docker/build-deb-amd64.sh
    - name: Upload build directory
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
  publish:
    name: Publish debian package
    if: github.event_name != 'pull_request'
    needs: build
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: python:3.7-slim-buster
    env:
      CLOUDSMITH_API_KEY: "${{ secrets.CLOUDSMITH_API_KEY }}"
      CLOUDSMITH_DEB_REPO: "${{ secrets.CLOUDSMITH_DEB_REPO }}"
    steps:
    - name: Check repository
      uses: actions/checkout@v1
    - name: Prepare cloudsmith-cli
      run: |
        pip3 install --upgrade cloudsmith-cli
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: Publish debian package
      run: |
        docker/publish-debs.sh
